{
    "contributors": [
        [
            "satempler", 
            "email"
        ], 
        [
            "stefanor", 
            "lexrank"
        ]
    ], 
    "title": "pyclean crashed with Exception in from_package(): cannot get content of python-wadllib", 
    "comments": [
        {
            "date": "2012-02-25 06:40:02", 
            "sentences": [
                {
                    "is_in_lex_summary": false, 
                    "text": "Tried to install Radeon (post-release updates) after a clean install\n", 
                    "is_in_email_summary": true
                }, 
                {
                    "is_in_lex_summary": true, 
                    "text": "ProblemType: Crash\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "Date: Sat Feb 25 00:28:15 2012\n", 
                    "is_in_email_summary": true
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "ExecutablePath: /usr/bin/pyclean\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "ExecutableTimestamp: 1324504889\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "InterpreterPath: /usr/bin/python2.7\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": true, 
                    "text": "ProcCmdline: /usr/bin/python /usr/bin/pyclean -p python-wadllib\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "ProcCwd: /\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "ProcEnviron:\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": " TERM=linux\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": " PATH=(custom, no user)\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": " LANG=en_US.UTF-8\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "PythonArgs: ['/usr/bin/pyclean', '-p', 'python-wadllib']\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "UserGroups:\n", 
                    "is_in_email_summary": false
                }
            ], 
            "name": "satempler", 
            "email": "satempler"
        }, 
        {
            "date": "2012-02-25 06:40:02", 
            "sentences": [], 
            "name": "satempler", 
            "email": "satempler"
        }, 
        {
            "date": "2012-03-04 08:56:44", 
            "sentences": [
                {
                    "is_in_lex_summary": false, 
                    "text": "Can you give some more information on what caused this?\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": true, 
                    "text": "You'll get that exception when running pyclean when wadllib isn't installed, but that should never happen.\n", 
                    "is_in_email_summary": true
                }
            ], 
            "name": "stefanor", 
            "email": "stefanor"
        }, 
        {
            "date": "2012-03-04 08:58:54", 
            "sentences": [
                {
                    "is_in_lex_summary": false, 
                    "text": "Thanks to bug 944078, this bug is missing lots of useful bits. ", 
                    "is_in_email_summary": true
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "What I'd really like to know is:\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "* What release are you on?\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": true, 
                    "text": "* What's the contents of /etc/apt/sources.list and /etc/apt/sources.list.d/*.list ?\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "* What's the output of dpkg -l python-wadllib?\n", 
                    "is_in_email_summary": false
                }
            ], 
            "name": "stefanor", 
            "email": "stefanor"
        }
    ], 
    "id": "940800", 
    "project": "Launchpad", 
    "original_link": "https://bugs.launchpad.net/ubuntu/+bug/940800"
}