{
    "contributors": [
        [
            "chris-bainbridge", 
            "email"
        ], 
        [
            "rye", 
            "lexrank"
        ], 
        [
            "daz-fuller", 
            "email"
        ], 
        [
            "chevrier-bertrand", 
            "lexrank"
        ]
    ], 
    "title": "exceptions.Exception: peer cant handle message 'ERROR'", 
    "comments": [
        {
            "date": "2012-02-17 10:40:44", 
            "sentences": [
                {
                    "is_in_lex_summary": false, 
                    "text": "ubuntuone-client        2.0.0-0ubuntu2.3 \n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": true, 
                    "text": "2012-02-17 10:20:47,074 - twisted - ERROR - Unhandled Error\n", 
                    "is_in_email_summary": true
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "Traceback (most recent call last):\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "  File \"/usr/lib/python2.7/dist-packages/twisted/python/log.py\", line 84, in callWithLogger\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "    return callWithContext({\"system\": lp}, func, *args, **kw)\n", 
                    "is_in_email_summary": true
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "  File \"/usr/lib/python2.7/dist-packages/twisted/python/log.py\", line 69, in callWithContext\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "    return context.call({ILogContext: newCtx}, func, *args, **kw)\n", 
                    "is_in_email_summary": true
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "  File \"/usr/lib/python2.7/dist-packages/twisted/python/context.py\", line 118, in callWithContext\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "  File \"/usr/lib/python2.7/dist-packages/twisted/python/context.py\", line 81, in callWithContext\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "    return func(*args,**kw)\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "--- <exception caught here> ---\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "  File \"/usr/lib/python2.7/dist-packages/twisted/internet/gtk2reactor.py\", line 288, in _doReadOrWrite\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "    why = source.doRead()\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "  File \"/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py\", line 137, in doRead\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "    return Connection.doRead(self)\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "  File \"/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py\", line 460, in doRead\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "    rval = self.protocol.dataReceived(data)\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "  File \"/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol/ubuntuone/storageprotocol/client.py\", line 1601, in dataReceived\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "    StorageClient.dataReceived(self, data)\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "  File \"/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol/ubuntuone/storageprotocol/client.py\", line 91, in dataReceived\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "    request.RequestHandler.dataReceived(self, data)\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": true, 
                    "text": "  File \"/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol/ubuntuone/storageprotocol/request.py\", line 143, in dataReceived\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "    self.buildMessage(data)\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "  File \"/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol/ubuntuone/storageprotocol/request.py\", line 163, in buildMessage\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "    self.buildMessage(data[:p])\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "  File \"/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol/ubuntuone/storageprotocol/request.py\", line 190, in buildMessage\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": true, 
                    "text": "    self.processMessage(message)\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "  File \"/usr/lib/python2.7/dist-packages/ubuntuone-client/ubuntuone/syncdaemon/action_queue.py\", line 272, in processMessage\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": true, 
                    "text": "    result = ThrottlingStorageClient.processMessage(self, message)\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "  File \"/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol/ubuntuone/storageprotocol/request.py\", line 232, in processMessage\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": true, 
                    "text": "    str(message).replace(\"\\n\", \" \")))\n", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": true, 
                    "text": "exceptions.Exception: peer cant handle message 'ERROR' {id: 7 type: ERROR error {   type: TRY_AGAIN   comment: \"TryAgain (RPCTimeoutError: )\" } }\n", 
                    "is_in_email_summary": false
                }
            ], 
            "name": "chris-bainbridge", 
            "email": "chris-bainbridge"
        }, 
        {
            "date": "2012-02-17 10:43:30", 
            "sentences": [
                {
                    "is_in_lex_summary": false, 
                    "text": "Looks similar to bug #589059 and bug #584461\n", 
                    "is_in_email_summary": false
                }
            ], 
            "name": "chris-bainbridge", 
            "email": "chris-bainbridge"
        }, 
        {
            "date": "2012-02-24 22:50:27", 
            "sentences": [
                {
                    "is_in_lex_summary": false, 
                    "text": "Status changed to 'Confirmed' because the bug affects multiple users.\n", 
                    "is_in_email_summary": false
                }
            ], 
            "name": "janitor", 
            "email": "janitor"
        }, 
        {
            "date": "2012-02-24 23:12:45", 
            "sentences": [], 
            "name": "chevrier-bertrand", 
            "email": "chevrier-bertrand"
        }, 
        {
            "date": "2012-02-25 11:46:33", 
            "sentences": [
                {
                    "is_in_lex_summary": false, 
                    "text": "This is a server-side response. ", 
                    "is_in_email_summary": false
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "The client action is to reconnect upon receiving this.\n", 
                    "is_in_email_summary": false
                }
            ], 
            "name": "rye", 
            "email": "rye"
        }, 
        {
            "date": "2012-02-26 16:32:45", 
            "sentences": [
                {
                    "is_in_lex_summary": true, 
                    "text": "I'm getting the same error in the log file, is there a resolution which doesn't involve completely removing and re-installing u1?\n", 
                    "is_in_email_summary": true
                }
            ], 
            "name": "daz-fuller", 
            "email": "daz-fuller"
        }, 
        {
            "date": "2012-02-26 17:07:54", 
            "sentences": [
                {
                    "is_in_lex_summary": true, 
                    "text": "Removing and reinstalling Ubuntu One client does not affect this error, this is the server-side response.\n", 
                    "is_in_email_summary": true
                }, 
                {
                    "is_in_lex_summary": false, 
                    "text": "The client will reconnect until it connects to the server instance that is able to provide the synchronization service.\n", 
                    "is_in_email_summary": true
                }
            ], 
            "name": "rye", 
            "email": "rye"
        }
    ], 
    "id": "934098", 
    "project": "Launchpad", 
    "original_link": "https://bugs.launchpad.net/ubuntu/+bug/934098"
}